authentication:
    path: /api/authentication
    methods: ['POST']

controller_admin:
    resource: ../src/Controller/Admin/*.php
    type: attribute
    prefix: /{_locale}/admin
    name_prefix: admin_
    requirements:
        _locale: '%app.locales%'
