services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $itemExtensions: !tagged_iterator 'app.api_platform.extension.query_collection'
      $collectionExtensions: !tagged_iterator 'app.api_platform.extension.query_collection'
  _instanceof:
    ApiPlatform\Doctrine\Orm\Extension\QueryItemExtensionInterface:
      tags: [ name: 'app.api_platform.extension.query_item' ]
    ApiPlatform\Doctrine\Orm\Extension\QueryCollectionExtensionInterface:
      tags: [ name: 'app.api_platform.extension.query_collection' ]
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/**/Model'
      - '../src/**/Exception'
      - '../src/Kernel.php'

  entity.listener:
    class: App\EventListener\EntityListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
