services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/**/Model'
      - '../src/**/Exception'
      - '../src/Utils/Twitter/Client.php'
      - '../src/Kernel.php'

  security.user_password_hasher:
    class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher
    public: true
    arguments:
      [ '@security.password_hasher_factory' ]

  App\DataFixtures\Providers\HashPasswordProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]
