services:
  _defaults:
    autowire: true

  security.user_password_hasher:
    class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher
    public: true
    arguments:
      [ '@security.password_hasher_factory' ]

  App\DataFixtures\Providers\HashPasswordProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]
