parameters:
  locale: 'en'
  app.locales: pl|en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $itemExtensions: !tagged_iterator 'app.api_platform.extension.query_collection'
      $collectionExtensions: !tagged_iterator 'app.api_platform.extension.query_collection'
  _instanceof:
    ApiPlatform\Doctrine\Orm\Extension\QueryItemExtensionInterface:
      tags: [ name: 'app.api_platform.extension.query_item' ]
    ApiPlatform\Doctrine\Orm\Extension\QueryCollectionExtensionInterface:
      tags: [ name: 'app.api_platform.extension.query_collection' ]
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/**/Model'
      - '../src/**/Exception'
      - '../src/Kernel.php'

  entity.listener:
    class: App\EventListener\EntityListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

  App\DataFixtures\Providers\HashPasswordProvider:
    tags: [ { name: nelmio_alice.faker.provider } ]

  ApiPlatform\Symfony\UriVariableTransformer\UuidUriVariableTransformer:
    tags:
      - { name: api_platform.uri_variables.transformer }
